### PR TITLE
Minor fixes and improvements

### PR DESCRIPTION
**Pull request by Qyg0n**
Hey there,
I found 2 bugs in your code [here](https://github.com/Ruhrpottpatriot/OnlineSubsystemEpic/compare/master...Qyg0n:pullreq2?expand=1#diff-601a48ef072194ed0301e8d985b49522L467) and [here](https://github.com/Ruhrpottpatriot/OnlineSubsystemEpic/compare/master...Qyg0n:pullreq2?expand=1#diff-8c9ee6558434793d2c3963c2a9c1821cL62)

The other changes are mostly just casts to uint32_t because compiling for linux was not possible without them.
Feel free to include or ignore them.

Cheers

### CODE REVIEW

**Comment by Ruhrpottpatriot** [comment]
1. Fixes seam reasonable, although, iirc UE4 correctly casting to `uint32` instead of `uint32_t` should be better.
2. Is there a reason you added 0.5 to the tick budget?

**Comment by Qyg0n** [comment]
1. I just needed a cast since no cast was throwing an error while compiling a linux server.
2. It's for rounding, since the cast just strips the decimals and therefore 1.9 would be rounded to 1 instead of two, adding 0.5 fixes that. It's not super important but I just added it with the cast.

**Comment by Ruhrpottpatriot** [comment]
Then please cast it to a floating point instead of just adding a 0.5. Doing that will actually change the behaviour of the code.
 A tick budget of zero means that tasks are done no matter how long they take, but by adding 0.5 your code will never get to that bun instead always use t + 0.5s as budget. This can introduce hard to spot bugs in client code.

The reason why you get this is because you convert a floating point type to an integer type, which incurs loss of data!

**Comment by Qyg0n** [comment]
Your absolutely right. I'm dumb.

**Comment by Ruhrpottpatriot** [comment]
I integrated the PR into the master branch. A few notes:
- I detected a bug with open session slots, fixed that
- Adding 0.5 and then casting to an integer is a bad way of rounding the value. I have added a proper way to convert the double from the config to an uint32_t
- I left the casts to uint32_t, since this is the type the SDK actually uses, so your code was correct from the beginning.

**Pull request merged**
